### ISSUE TITLE
I have question related to Prompt

### ISSUE THREAD

**Issue by ajmal-yazdani** [Ami343/ChatCopilot#2]
First of all, Thanks a lot for the all the great work you have shown here.

Is there any writeup on some basic code explanation?

Could you please give me some information on below:

"Prompt": {
  "KnowledgeCutOffDate": "",
  "SystemDescription": "",
  "SystemResponse": "",
  "SystemIntent": "",
  "InitialBotMessage": "",
  "SystemIntentContinuation": "",
  "PromptTimeoutInSeconds": 10
},

Also, can I show the "prompt" which we're sending to LLM in logs just to see what going on?

Thanks.

**Comment by Ami343** [comment]
Thank you for your kind word and rising this issue. I linked PR in which I pushed the example configuration for 'Prompt' and change in log level for 'Microsoft.SemanticKernel'. Please find additional explanation below.

### Explanation
'Prompt' is a set of system instructions and bot persona. In this way you instruct LLM how it should behave and respond to the user request. It is based on the microsoft [chat-copilot](https://github.com/microsoft/chat-copilot/tree/main) proposed configuration with tiny changes. 

"Prompt": {
"KnowledgeCutOffDate": "", // Date to which bot have a knowledge
"SystemDescription": "", // Instruction for bot
"SystemResponse": "", // Instruction for how bot responds to user requests
"SystemIntent": "", // Instruction for user intent extraction from chat history
"InitialBotMessage": "", // The initial message from the bot sent to the user
"SystemIntentContinuation": "", // Part of the user intent extraction from chat history
"PromptTimeoutInSeconds": 10 // Timeout for calls to SK api 
}

Regarding logging behaviour. You can change logging by setting log level for 'Microsoft.SemanticKernel' ( please check this article for more details [link](https://devblogs.microsoft.com/semantic-kernel/unlock-the-power-of-telemetry-in-semantic-kernel-sdk/) ). In appsettings.Example.json it's set to 'Information'. For the most verbose level set it to 'Trace'. If those logs are not sufficient, in upcoming future we are planning to introduce telemetry so we can take into consideration adding some custom logs.

### Next Steps
@hubertbodek please merge the linked [PR](https://github.com/Ami343/ChatCopilot/pull/4) to resolve this issue. 

### Closing Note
Thanks for bringing this to our attention!

**Comment by ajmal-yazdani** [comment]
Thank you very much. Appreciate!
